channels:
  - conda-forge
  - bioconda
  - nodefaults
# there are strictly no dependencies for this wrapper, but
# the tests require a environment.yaml with 
# dependencies. So this is just to please the tests :)
dependencies:
  - python >=3.8
  
